spring:
  profiles:
    active:
    -dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springconfig-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
---
server:
  port: 8202
spring:
  profiles: pro
  application:
    name: springconfig-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka